// Catalog of object metaphors with their prompts, summary templates,
// and glossary. Append-only; new metaphors don't require code changes
// elsewhere.
import type { MetaphorTemplate } from "./types";

export const METAPHORS: MetaphorTemplate[] = [
  {
    id: "bucket",
    noun: "bucket",
    pluralNoun: "buckets",
    article: "a",
    blurb: "A spot where things pile up until you do something with them.",
    shape: "bucket",
    prompts: [
      {
        id: "bucket_what",
        question: "What goes in the bucket?",
        helper: "The kinds of things you'd drop in.",
        example: "draft notes, photos, a link to a song",
        category: "entities",
        specLabel: "Items collected",
        summaryTemplate: "The {noun} holds {answer}.",
      },
      {
        id: "bucket_who",
        question: "Who can drop things in?",
        helper: "People or roles who add to the bucket.",
        example: "anyone in the band, just me, the kids",
        category: "actors",
        specLabel: "Who can add",
        summaryTemplate: "{answer} can drop things in.",
      },
      {
        id: "bucket_when",
        question: "When do you empty it?",
        helper: "What triggers a clear-out.",
        example: "every Sunday, when it's full, before a meeting",
        category: "triggers",
        specLabel: "When it empties",
        summaryTemplate: "The {noun} gets emptied {answer}.",
      },
      {
        id: "bucket_do",
        question: "What do you do with what's inside?",
        helper: "What happens to the contents.",
        example: "sort by colour, file the keepers, archive the rest",
        category: "actions",
        specLabel: "What happens to contents",
        summaryTemplate: "When it empties, you {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the bucket", spec: "the collection", category: "entities" },
      { metaphor: "drops in", spec: "add-item action", category: "actions" },
      { metaphor: "empties", spec: "archive event", category: "triggers" },
      { metaphor: "what's inside", spec: "items", category: "entities" },
    ],
  },
  {
    id: "shelf",
    noun: "shelf",
    pluralNoun: "shelves",
    article: "a",
    blurb: "A place where things sit on display, in some kind of order.",
    shape: "shelf",
    prompts: [
      {
        id: "shelf_what",
        question: "What sits on the shelf?",
        helper: "The things that live there in plain view.",
        example: "books, jars of tea, cassette tapes",
        category: "entities",
        specLabel: "Items on display",
        summaryTemplate: "The {noun} holds {answer}.",
      },
      {
        id: "shelf_arr",
        question: "How is it arranged?",
        helper: "What order the things are in.",
        example: "by colour, by date, oldest on the left",
        category: "actions",
        specLabel: "How items are ordered",
        summaryTemplate: "Things are arranged {answer}.",
      },
      {
        id: "shelf_who",
        question: "Who reaches for things?",
        helper: "People who take things off the shelf.",
        example: "the kitchen crew, anyone passing by",
        category: "actors",
        specLabel: "Who can take items",
        summaryTemplate: "{answer} reach for things.",
      },
      {
        id: "shelf_down",
        question: "When does something come down?",
        helper: "What triggers a thing leaving the shelf.",
        example: "when it's used up, at the end of the season",
        category: "triggers",
        specLabel: "When items leave",
        summaryTemplate: "Something comes down {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the shelf", spec: "the catalog", category: "entities" },
      { metaphor: "sits on", spec: "is stored", category: "entities" },
      { metaphor: "reach for", spec: "retrieve action", category: "actions" },
      { metaphor: "comes down", spec: "remove event", category: "triggers" },
    ],
  },
  {
    id: "jar",
    noun: "jar",
    pluralNoun: "jars",
    article: "a",
    blurb: "A sealed container you keep one kind of thing in.",
    shape: "jar",
    prompts: [
      {
        id: "jar_what",
        question: "What's in the jar?",
        helper: "The one thing you keep inside.",
        example: "next year's seeds, voice memos, recipes",
        category: "entities",
        specLabel: "What it preserves",
        summaryTemplate: "The {noun} keeps {answer}.",
      },
      {
        id: "jar_in",
        question: "How do you put things in?",
        helper: "How items get added.",
        example: "labelled with a date, one at a time",
        category: "actions",
        specLabel: "How items are added",
        summaryTemplate: "Things go in {answer}.",
      },
      {
        id: "jar_open",
        question: "When do you open it?",
        helper: "What triggers a look inside.",
        example: "in the spring, when someone asks",
        category: "triggers",
        specLabel: "When it opens",
        summaryTemplate: "The {noun} opens {answer}.",
      },
      {
        id: "jar_who",
        question: "Who's allowed to open it?",
        helper: "People with the lid.",
        example: "just the keeper, the family, anyone",
        category: "actors",
        specLabel: "Who can open it",
        summaryTemplate: "{answer} can open it.",
      },
    ],
    glossary: [
      { metaphor: "the jar", spec: "the archive", category: "entities" },
      { metaphor: "put in", spec: "preserve action", category: "actions" },
      { metaphor: "open", spec: "read event", category: "triggers" },
      { metaphor: "the keeper", spec: "the owner", category: "actors" },
    ],
  },
  {
    id: "deck",
    noun: "deck",
    pluralNoun: "decks",
    article: "a",
    blurb: "A stack of cards you draw from, one at a time.",
    shape: "deck",
    prompts: [
      {
        id: "deck_card",
        question: "What's printed on each card?",
        helper: "What one card stands for.",
        example: "a question, a chore, a name to call",
        category: "entities",
        specLabel: "What each item is",
        summaryTemplate: "Each card shows {answer}.",
      },
      {
        id: "deck_add",
        question: "How are cards added to the deck?",
        helper: "Where new cards come from.",
        example: "added by the team, written on the spot",
        category: "actions",
        specLabel: "How items are added",
        summaryTemplate: "Cards are added {answer}.",
      },
      {
        id: "deck_draw",
        question: "How do you draw a card?",
        helper: "Who picks one and how.",
        example: "the next person up, at random",
        category: "actors",
        specLabel: "Who draws and how",
        summaryTemplate: "Cards are drawn {answer}.",
      },
      {
        id: "deck_reset",
        question: "When does the deck reset?",
        helper: "What triggers a reshuffle.",
        example: "when it runs out, every morning",
        category: "triggers",
        specLabel: "When it resets",
        summaryTemplate: "The {noun} resets {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the deck", spec: "the queue", category: "entities" },
      { metaphor: "a card", spec: "an item", category: "entities" },
      { metaphor: "draw", spec: "pick-next action", category: "actions" },
      { metaphor: "reset", spec: "reshuffle event", category: "triggers" },
    ],
  },
  {
    id: "board",
    noun: "board",
    pluralNoun: "boards",
    article: "a",
    blurb: "A wall everyone glances at to see what's up.",
    shape: "board",
    prompts: [
      {
        id: "board_pin",
        question: "What gets pinned to the board?",
        helper: "The kinds of notes that go up.",
        example: "shift swaps, weather notes, prayers",
        category: "entities",
        specLabel: "What gets posted",
        summaryTemplate: "The {noun} shows {answer}.",
      },
      {
        id: "board_who_pins",
        question: "Who pins things up?",
        helper: "People who add notes.",
        example: "any worker, just the lead",
        category: "actors",
        specLabel: "Who can post",
        summaryTemplate: "{answer} pin things up.",
      },
      {
        id: "board_who_reads",
        question: "Who looks at it?",
        helper: "People who read the board.",
        example: "everyone walking past, the morning crew",
        category: "actors",
        specLabel: "Who reads it",
        summaryTemplate: "{answer} look at it.",
      },
      {
        id: "board_down",
        question: "When does something come down?",
        helper: "What triggers a note leaving.",
        example: "after a week, once the job's done",
        category: "triggers",
        specLabel: "When notes leave",
        summaryTemplate: "Notes come down {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the board", spec: "the view", category: "entities" },
      { metaphor: "pin", spec: "post action", category: "actions" },
      { metaphor: "come down", spec: "remove event", category: "triggers" },
    ],
  },
  {
    id: "drawer",
    noun: "drawer",
    pluralNoun: "drawers",
    article: "a",
    blurb: "Something you tuck away, then pull open later.",
    shape: "drawer",
    prompts: [
      {
        id: "drawer_what",
        question: "What gets put away in the drawer?",
        helper: "The kinds of things you tuck in.",
        example: "old receipts, kids' drawings, spare keys",
        category: "entities",
        specLabel: "What's stored",
        summaryTemplate: "The {noun} holds {answer}.",
      },
      {
        id: "drawer_who",
        question: "Who puts things in?",
        helper: "People who add to the drawer.",
        example: "anyone in the house, just the bookkeeper",
        category: "actors",
        specLabel: "Who files things",
        summaryTemplate: "{answer} put things in.",
      },
      {
        id: "drawer_find",
        question: "How do you find something in there?",
        helper: "How you look things up.",
        example: "by name, by date, by colour of folder",
        category: "actions",
        specLabel: "How items are looked up",
        summaryTemplate: "Things are found {answer}.",
      },
      {
        id: "drawer_clean",
        question: "When do you clean it out?",
        helper: "What triggers a clear-out.",
        example: "once a year, when it won't close",
        category: "triggers",
        specLabel: "When it gets cleaned out",
        summaryTemplate: "The {noun} gets cleaned {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the drawer", spec: "the store", category: "entities" },
      { metaphor: "put away", spec: "file action", category: "actions" },
      { metaphor: "find", spec: "search action", category: "actions" },
      { metaphor: "clean out", spec: "archive event", category: "triggers" },
    ],
  },
  {
    id: "basket",
    noun: "basket",
    pluralNoun: "baskets",
    article: "a",
    blurb: "A bunch of things gathered together to carry somewhere.",
    shape: "basket",
    prompts: [
      {
        id: "basket_what",
        question: "What goes in the basket?",
        helper: "The kinds of things you gather.",
        example: "the morning's berries, the day's mail",
        category: "entities",
        specLabel: "Items gathered",
        summaryTemplate: "The {noun} gathers {answer}.",
      },
      {
        id: "basket_who",
        question: "Who fills it?",
        helper: "People doing the gathering.",
        example: "the pickers, whoever's free",
        category: "actors",
        specLabel: "Who fills it",
        summaryTemplate: "{answer} fill it.",
      },
      {
        id: "basket_sort",
        question: "How do you sort what's in it?",
        helper: "How the contents are split up.",
        example: "by ripeness, by name, by who needs it",
        category: "actions",
        specLabel: "How contents are sorted",
        summaryTemplate: "The contents are sorted {answer}.",
      },
      {
        id: "basket_where",
        question: "Where does it end up?",
        helper: "What happens after it's full.",
        example: "the kitchen, the office, the freezer",
        category: "triggers",
        specLabel: "Where it goes when full",
        summaryTemplate: "When full, it ends up {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the basket", spec: "the batch", category: "entities" },
      { metaphor: "fill", spec: "add-item action", category: "actions" },
      { metaphor: "sort", spec: "categorize action", category: "actions" },
      { metaphor: "ends up", spec: "destination event", category: "triggers" },
    ],
  },
  {
    id: "stack",
    noun: "stack",
    pluralNoun: "stacks",
    article: "a",
    blurb: "A pile where new things land on top of old things.",
    shape: "stack",
    prompts: [
      {
        id: "stack_what",
        question: "What lands on the stack?",
        helper: "The kinds of things that get added.",
        example: "fresh notes, today's slips, new requests",
        category: "entities",
        specLabel: "What gets added",
        summaryTemplate: "The {noun} grows with {answer}.",
      },
      {
        id: "stack_top",
        question: "How do new things land?",
        helper: "How items get added to the top.",
        example: "dropped on top, slipped on by hand",
        category: "actions",
        specLabel: "How items are added",
        summaryTemplate: "New things land {answer}.",
      },
      {
        id: "stack_take",
        question: "When do you take something off?",
        helper: "What triggers a pull from the top.",
        example: "when there's time, at the start of a shift",
        category: "triggers",
        specLabel: "When items are taken",
        summaryTemplate: "Things come off the top {answer}.",
      },
      {
        id: "stack_who",
        question: "Who works the stack?",
        helper: "People who add to or pull from it.",
        example: "the on-duty person, just the elder",
        category: "actors",
        specLabel: "Who adds and pulls",
        summaryTemplate: "{answer} works the {noun}.",
      },
    ],
    glossary: [
      { metaphor: "the stack", spec: "the queue", category: "entities" },
      { metaphor: "land on top", spec: "push action", category: "actions" },
      { metaphor: "take off", spec: "pop action", category: "actions" },
      { metaphor: "the top", spec: "the latest", category: "entities" },
    ],
  },
  {
    id: "folder",
    noun: "folder",
    pluralNoun: "folders",
    article: "a",
    blurb: "Papers grouped together under one label.",
    shape: "folder",
    prompts: [
      {
        id: "folder_what",
        question: "What papers go in the folder?",
        helper: "The kinds of pages grouped together.",
        example: "intake forms, photos, copies of the contract",
        category: "entities",
        specLabel: "What's grouped",
        summaryTemplate: "The {noun} holds {answer}.",
      },
      {
        id: "folder_label",
        question: "Who labels it, and what does the label say?",
        helper: "Where the name on the front comes from.",
        example: "the family writes it, the program lead names it",
        category: "actors",
        specLabel: "Who names the group",
        summaryTemplate: "The label is set by {answer}.",
      },
      {
        id: "folder_open",
        question: "Who can open it?",
        helper: "People with permission to read inside.",
        example: "just the worker, the family, the band office",
        category: "actors",
        specLabel: "Who can read it",
        summaryTemplate: "{answer} can open it.",
      },
      {
        id: "folder_filed",
        question: "When does it get filed away?",
        helper: "What triggers tucking the folder out of sight.",
        example: "when the case is closed, at year-end",
        category: "triggers",
        specLabel: "When it's archived",
        summaryTemplate: "The {noun} gets filed {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the folder", spec: "the group", category: "entities" },
      { metaphor: "papers", spec: "documents", category: "entities" },
      { metaphor: "label", spec: "group name", category: "entities" },
      { metaphor: "filed away", spec: "archive event", category: "triggers" },
    ],
  },
  {
    id: "thread",
    noun: "thread",
    pluralNoun: "threads",
    article: "a",
    blurb: "A back-and-forth that keeps the same set of people together.",
    shape: "thread",
    prompts: [
      {
        id: "thread_who",
        question: "Who's on the thread?",
        helper: "The people kept together by it.",
        example: "the parents, the homeschool circle",
        category: "actors",
        specLabel: "Who's included",
        summaryTemplate: "{answer} are on the {noun}.",
      },
      {
        id: "thread_start",
        question: "What kicks the thread off?",
        helper: "How a new conversation begins.",
        example: "a question from anyone, a weekly check-in",
        category: "triggers",
        specLabel: "What starts a thread",
        summaryTemplate: "A {noun} starts when {answer}.",
      },
      {
        id: "thread_reply",
        question: "Who can reply, and how?",
        helper: "How messages get added.",
        example: "anyone on it, only adults, voice notes",
        category: "actions",
        specLabel: "How replies are added",
        summaryTemplate: "Replies come from {answer}.",
      },
      {
        id: "thread_close",
        question: "When does the thread close?",
        helper: "What signals it's done.",
        example: "when the question's answered, after a week of quiet",
        category: "triggers",
        specLabel: "When it ends",
        summaryTemplate: "The {noun} closes {answer}.",
      },
    ],
    glossary: [
      { metaphor: "the thread", spec: "the conversation", category: "entities" },
      { metaphor: "kicks off", spec: "start event", category: "triggers" },
      { metaphor: "reply", spec: "message action", category: "actions" },
      { metaphor: "closes", spec: "end event", category: "triggers" },
    ],
  },
];

// A generic adaptive prompt set the "Describe your own object" path uses.
// Each prompt template uses {noun} so the question reads in the
// practitioner's chosen vocabulary.
export const CUSTOM_PROMPTS = [
  {
    id: "custom_what",
    question: "What goes in the {noun}?",
    helper: "The kinds of things this {noun} holds.",
    example: "list a few",
    category: "entities" as const,
    specLabel: "What it holds",
    summaryTemplate: "The {noun} holds {answer}.",
  },
  {
    id: "custom_who",
    question: "Who puts things in or takes them out?",
    helper: "The people who interact with the {noun}.",
    example: "name the people or roles",
    category: "actors" as const,
    specLabel: "Who interacts with it",
    summaryTemplate: "{answer} interact with the {noun}.",
  },
  {
    id: "custom_when",
    question: "When does the {noun} change?",
    helper: "What triggers something happening to it.",
    example: "name the moments",
    category: "triggers" as const,
    specLabel: "When it changes",
    summaryTemplate: "The {noun} changes {answer}.",
  },
  {
    id: "custom_do",
    question: "What happens then?",
    helper: "What gets done with the {noun} or its contents.",
    example: "describe the actions",
    category: "actions" as const,
    specLabel: "What happens",
    summaryTemplate: "When that happens, you {answer}.",
  },
];

export function getMetaphorById(id: string | null): MetaphorTemplate | null {
  if (!id) return null;
  return METAPHORS.find((m) => m.id === id) ?? null;
}

// Build a runtime template for a custom-noun session: clones the generic
// prompts and substitutes {noun}. Glossary is intentionally minimal — the
// user named their own object, we don't presume mappings beyond the
// noun itself.
export function buildCustomTemplate(
  noun: string,
  article: "a" | "an",
): MetaphorTemplate {
  const cleaned = noun.trim() || "thing";
  const sub = (s: string) => s.replaceAll("{noun}", cleaned);
  return {
    id: "custom",
    noun: cleaned,
    pluralNoun: cleaned + "s",
    article,
    blurb: `A ${cleaned} you described in your own words.`,
    shape: "custom",
    prompts: CUSTOM_PROMPTS.map((p) => ({
      id: p.id,
      question: sub(p.question),
      helper: sub(p.helper),
      example: p.example,
      category: p.category,
      specLabel: p.specLabel,
      // Keep {noun} live in summaryTemplate so summary still substitutes.
      summaryTemplate: p.summaryTemplate,
    })),
    glossary: [
      { metaphor: `the ${cleaned}`, spec: "the thing", category: "entities" },
    ],
  };
}
