import sys

def resolve():
    path = "artifacts/practitioner-operating-plan/src/pages/SaltMonthlyClose.tsx"
    with open(path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    # The point where the conflict starts is line 804 (index 803)
    # The conflict has completely messed up the rest of the file after that point.
    
    start_lines = lines[:803]

    # I will re-construct the remaining part of the file from scratch correctly.
    resolved_body = [
        "                  <table style={{ width: \"100%\", borderCollapse: \"collapse\", fontSize: \"9pt\" }}>\n",
        "                    <thead>\n",
        "                      <tr style={{ borderBottom: `1.5pt solid ${RULE}`, color: MUTED, fontWeight: 600, fontSize: \"7.5pt\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", letterSpacing: \"0.12em\", textTransform: \"uppercase\" }}>\n",
        "                        <th style={{ padding: \"3pt 4pt\", textAlign: \"left\",  width: \"25%\" }}>Channel</th>\n",
        "                        <th style={{ padding: \"3pt 4pt\", textAlign: \"right\", width: \"22%\" }}>Gross</th>\n",
        "                        <th style={{ padding: \"3pt 4pt\", textAlign: \"right\", width: \"20%\" }}>Refunds</th>\n",
        "                        <th style={{ padding: \"3pt 4pt\", textAlign: \"right\", width: \"20%\" }}>Net</th>\n",
        "                        <th className=\"print:hidden\" style={{ padding: \"3pt 4pt\", textAlign: \"right\", width: \"13%\" }}>Δ vs prior</th>\n",
        "                      </tr>\n",
        "                    </thead>\n",
        "                    <tbody>\n",
        "                      {channelTotals.map(row => {\n",
        "                        const hasDelta = row.delta !== null && Math.round(row.delta) !== 0;\n",
        "                        const rowBg = row.flashRow ? DELTA_FLASH : \"transparent\";\n",
        "                        return (\n",
        "                          <tr key={row.source} style={{ borderBottom: `0.5pt solid ${RULE}`, background: rowBg, transition: \"background 0.4s ease\" }}>\n",
        "                            <td style={{ padding: \"5pt 4pt\", fontWeight: 600 }}>{SOURCE_META[row.source].label}</td>\n",
        "                            <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\" }}>\n",
        "                              {row.grossSales !== 0 ? fmt(row.grossSales) : \"—\"}\n",
        "                            </td>\n",
        "                            <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", color: row.refunds !== 0 ? RED : MUTED }}>\n",
        "                              {row.refunds !== 0 ? `(${fmt(row.refunds)})` : \"—\"}\n",
        "                            </td>\n",
        "                            <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", color: row.net >= 0 ? DARK : RED }}>\n",
        "                              {row.net !== 0 ? (row.net < 0 ? `(${fmt(row.net)})` : fmt(row.net)) : \"—\"}\n",
        "                            </td>\n",
        "                            <td className=\"print:hidden\" style={{ padding: \"5pt 4pt\", textAlign: \"right\" }}>\n",
        "                              {hasDelta && row.delta !== null ? (\n",
        "                                <span style={{ display: \"inline-block\", padding: \"1pt 5pt\", borderRadius: \"2pt\", background: row.delta >= 0 ? DELTA_POS_BG : DELTA_NEG_BG, color: row.delta >= 0 ? GREEN : RED, fontSize: \"7.5pt\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", letterSpacing: \"0.04em\" }}>\n",
        "                                  {fmtDelta(row.delta)}\n",
        "                                </span>\n",
        "                              ) : row.delta === 0 ? (\n",
        "                                <span style={{ fontSize: \"7.5pt\", color: MUTED }}>no change</span>\n",
        "                              ) : (\n",
        "                                <span style={{ fontSize: \"7.5pt\", color: MUTED }}>—</span>\n",
        "                              )}\n",
        "                            </td>\n",
        "                          </tr>\n",
        "                        );\n",
        "                      })}\n",
        "                      <tr style={{ borderTop: `1.5pt solid ${RULE}`, background: \"rgba(31,61,46,0.04)\" }}>\n",
        "                        <td style={{ padding: \"5pt 4pt\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", fontSize: \"8pt\", letterSpacing: \"0.06em\", textTransform: \"uppercase\", color: DARK }}>Total</td>\n",
        "                        <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\" }}>\n",
        "                          {fmt(channelTotals.reduce((s, r) => s + r.grossSales, 0))}\n",
        "                        </td>\n",
        "                        <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", color: RED }}>\n",
        "                          {channelTotals.some(r => r.refunds !== 0)\n",
        "                            ? `(${fmt(channelTotals.reduce((s, r) => s + Math.abs(r.refunds), 0))})`\n",
        "                            : \"—\"}\n",
        "                        </td>\n",
        "                        <td style={{ padding: \"5pt 4pt\", textAlign: \"right\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", color: totalNet >= 0 ? GREEN : RED }}>\n",
        "                          {totalNet < 0 ? `(${fmt(totalNet)})` : fmt(totalNet)}\n",
        "                        </td>\n",
        "                        <td className=\"print:hidden\" style={{ padding: \"5pt 4pt\" }} />\n",
        "                      </tr>\n",
        "                    </tbody>\n",
        "                  </table>\n",
        "                  <div className=\"print:hidden\" style={{ marginTop: \"6pt\", fontSize: \"7pt\", color: MUTED, fontStyle: \"italic\" }}>\n",
        "                    Δ column shows net change from the prior snapshot for each channel.\n",
        "                    Hidden in print — the filed record shows only the resulting numbers.\n",
        "                  </div>\n",
        "                </div>\n",
        "              </>\n",
        "            )}\n",
        "\n",
        "            <div style={{ marginBottom: \"20pt\" }}>\n",
        "              <div style={{ fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", fontSize: \"8pt\", fontWeight: 600, letterSpacing: \"0.2em\", textTransform: \"uppercase\", color: AMBER, marginBottom: \"12pt\" }}>\n",
        "                File a month\n",
        "              </div>\n",
        "\n",
        "              <form onSubmit={handleSubmit}>\n",
        "                <div style={{ display: \"grid\", gridTemplateColumns: \"1fr 1fr 1fr\", gap: \"12pt\", marginBottom: \"12pt\" }}>\n",
        "                  <div>\n",
        "                    <label style={labelStyle}>Month</label>\n",
        "                    <input\n",
        "                      type=\"month\"\n",
        "                      value={month}\n",
        "                      onChange={e => { setMonth(e.target.value); setFromImport(false); }}\n",
        "                      required\n",
        "                      style={inputStyle}\n",
        "                    />\n",
        "                  </div>\n",
        "                  <div>\n",
        "                    <label style={labelStyle}>\n",
        "                      Salt Revenue ($)\n",
        "                      {(hasAnyApplied || fromImport) && (\n",
        "                        <span className=\"print:hidden\" style={{ marginLeft: \"5pt\", fontWeight: 400, color: GREEN, letterSpacing: 0, textTransform: \"none\" }}>\n",
        "                          ← from channels\n",
        "                        </span>\n",
        "                      )}\n",
        "                    </label>\n",
        "                    <input\n",
        "                      type=\"number\"\n",
        "                      min=\"0\"\n",
        "                      step=\"0.01\"\n",
        "                      placeholder=\"e.g. 3200\"\n",
        "                      value={revenue}\n",
        "                      onChange={e => { setRevenue(e.target.value); setFromImport(false); }}\n",
        "                      required\n",
        "                      style={inputStyle}\n",
        "                    />\n",
        "                  </div>\n",
        "                  <div>\n",
        "                    <label style={labelStyle}>Salt Expenses ($)</label>\n",
        "                    <input\n",
        "                      type=\"number\"\n",
        "                      min=\"0\"\n",
        "                      step=\"0.01\"\n",
        "                      placeholder=\"e.g. 1800\"\n",
        "                      value={expenses}\n",
        "                      onChange={e => setExpenses(e.target.value)}\n",
        "                      style={inputStyle}\n",
        "                    />\n",
        "                  </div>\n",
        "                </div>\n",
        "\n",
        "                <div style={{ display: \"grid\", gridTemplateColumns: \"2fr 1fr\", gap: \"12pt\", marginBottom: \"12pt\", alignItems: \"end\" }}>\n",
        "                  <div>\n",
        "                    <label style={labelStyle}>Note (optional)</label>\n",
        "                    <input\n",
        "                      type=\"text\"\n",
        "                      placeholder=\"e.g. low inventory mid-month; back orders resolved\"\n",
        "                      value={note}\n",
        "                      onChange={e => setNote(e.target.value)}\n",
        "                      style={inputStyle}\n",
        "                    />\n",
        "                  </div>\n",
        "\n",
        "                  {revenue && (\n",
        "                    <div style={{ padding: \"5pt 8pt\", background: \"rgba(31,61,46,0.05)\", border: `1pt solid ${RULE}`, borderRadius: \"3pt\" }}>\n",
        "                      <div style={{ fontSize: \"7pt\", fontWeight: 700, letterSpacing: \"0.18em\", textTransform: \"uppercase\", color: MUTED, marginBottom: \"2pt\" }}>Net preview</div>\n",
        "                      <div style={{ fontSize: \"13pt\", fontWeight: 700, color: net >= 0 ? DARK : RED, fontFamily: \"Fraunces, Georgia, serif\" }}>\n",
        "                        {net >= 0 ? fmt(net) : `(${fmt(Math.abs(net))})`}\n",
        "                      </div>\n",
        "                      <div style={{ fontSize: \"7.5pt\", color: MUTED }}>vs. {fmt(SALT_BASELINE_NET)} baseline</div>\n",
        "                    </div>\n",
        "                  )}\n",
        "                </div>\n",
        "\n",
        "                <div style={{ display: \"flex\", gap: \"10pt\", alignItems: \"center\" }}>\n",
        "                  <button\n",
        "                    type=\"submit\"\n",
        "                    style={{ padding: \"6pt 18pt\", background: AMBER, color: CREAM, border: \"none\", borderRadius: \"3pt\", fontSize: \"8pt\", fontWeight: 700, letterSpacing: \"0.04em\", cursor: \"pointer\" }}\n",
        "                  >\n",
        "                    {saved ? \"Filed ✓\" : \"File this month\"}\n",
        "                  </button>\n",
        "\n",
        "                  <button\n",
        "                    type=\"button\"\n",
        "                    onClick={handleReset}\n",
        "                    style={{\n",
        "                      padding: \"6pt 14pt\",\n",
        "                      background: \"transparent\",\n",
        "                      color: confirmReset ? RED : MUTED,\n",
        "                      border: `1pt solid ${confirmReset ? RED : RULE}`,\n",
        "                      borderRadius: \"3pt\",\n",
        "                      fontSize: \"8pt\",\n",
        "                      fontWeight: confirmReset ? 700 : 400,\n",
        "                      cursor: \"pointer\",\n",
        "                    }}\n",
        "                  >\n",
        "                    {confirmReset ? \"Confirm reset — clears history + snapshots\" : \"Reset all\"}\n",
        "                  </button>\n",
        "\n",
        "                  {confirmReset && (\n",
        "                    <button\n",
        "                      type=\"button\"\n",
        "                      onClick={() => setConfirmReset(false)}\n",
        "                      style={{ fontSize: \"8pt\", color: MUTED, background: \"transparent\", border: \"none\", cursor: \"pointer\" }}\n",
        "                    >\n",
        "                      Cancel\n",
        "                    </button>\n",
        "                  )}\n",
        "                </div>\n",
        "              </form>\n",
        "            </div>\n",
        "\n",
        "            {/* ── Filed months history ──────────────────────────────────── */}\n",
        "            <div style={{ marginBottom: \"18pt\" }}>\n",
        "              <input\n",
        "                ref={importInputRef}\n",
        "                type=\"file\"\n",
        "                accept=\".json,application/json\"\n",
        "                style={{ display: \"none\" }}\n",
        "                onChange={handleImportFile}\n",
        "              />\n",
        "\n",
        "              <div className=\"print:hidden\" style={{ display: \"flex\", justifyContent: \"space-between\", alignItems: \"center\", marginBottom: \"8pt\", flexWrap: \"wrap\", gap: \"6pt\" }}>\n",
        "                <div style={{ fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", fontSize: \"8pt\", fontWeight: 600, letterSpacing: \"0.2em\", textTransform: \"uppercase\", color: AMBER }}>\n",
        "                  Filed months ({history.length})\n",
        "                </div>\n",
        "                <div style={{ display: \"flex\", gap: \"6pt\", flexWrap: \"wrap\" }}>\n",
        "                  <button\n",
        "                    type=\"button\"\n",
        "                    onClick={handleDownloadCSV}\n",
        "                    disabled={history.length === 0}\n",
        "                    title=\"Download history as a spreadsheet-ready CSV\"\n",
        "                    style={{\n",
        "                      padding: \"3pt 10pt\",\n",
        "                      background: history.length > 0 ? DARK : RULE,\n",
        "                      color: CREAM,\n",
        "                      border: \"none\",\n",
        "                      borderRadius: \"3pt\",\n",
        "                      fontSize: \"7.5pt\",\n",
        "                      fontWeight: 700,\n",
        "                      cursor: history.length > 0 ? \"pointer\" : \"default\",\n",
        "                      letterSpacing: \"0.03em\",\n",
        "                    }}\n",
        "                  >\n",
        "                    Download CSV\n",
        "                  </button>\n",
        "                  <button\n",
        "                    type=\"button\"\n",
        "                    onClick={handleDownloadJSON}\n",
        "                    disabled={history.length === 0}\n",
        "                    title=\"Download history as a JSON backup\"\n",
        "                    style={{\n",
        "                      padding: \"3pt 10pt\",\n",
        "                      background: \"transparent\",\n",
        "                      color: history.length > 0 ? DARK : MUTED,\n",
        "                      border: `1pt solid ${RULE}`,\n",
        "                      borderRadius: \"3pt\",\n",
        "                      fontSize: \"7.5pt\",\n",
        "                      fontWeight: 600,\n",
        "                      cursor: history.length > 0 ? \"pointer\" : \"default\",\n",
        "                      letterSpacing: \"0.03em\",\n",
        "                    }}\n",
        "                  >\n",
        "                    Download JSON\n",
        "                  </button>\n",
        "                  <button\n",
        "                    type=\"button\"\n",
        "                    onClick={handleImportClick}\n",
        "                    title=\"Restore history from a previously exported JSON file\"\n",
        "                    style={{\n",
        "                      padding: \"3pt 10pt\",\n",
        "                      background: \"transparent\",\n",
        "                      color: AMBER,\n",
        "                      border: `1pt solid ${AMBER}`,\n",
        "                      borderRadius: \"3pt\",\n",
        "                      fontSize: \"7.5pt\",\n",
        "                      fontWeight: 600,\n",
        "                      cursor: \"pointer\",\n",
        "                      letterSpacing: \"0.03em\",\n",
        "                    }}\n",
        "                  >\n",
        "                    Import JSON\n",
        "                  </button>\n",
        "                  {history.length > 0 && (\n",
        "                    <button\n",
        "                      type=\"button\"\n",
        "                      onClick={() => navigate(`${BASE}/tools/salt-yearly`)}\n",
        "                      style={{\n",
        "                        background: \"transparent\",\n",
        "                        border: `1pt solid ${AMBER}`,\n",
        "                        color: AMBER,\n",
        "                        borderRadius: \"3pt\",\n",
        "                        padding: \"3pt 10pt\",\n",
        "                        fontSize: \"7.5pt\",\n",
        "                        fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\",\n",
        "                        fontWeight: 700,\n",
        "                        letterSpacing: \"0.03em\",\n",
        "                        textTransform: \"uppercase\",\n",
        "                        cursor: \"pointer\",\n",
        "                      }}\n",
        "                    >\n",
        "                      Yearly summary →\n",
        "                    </button>\n",
        "                  )}\n",
        "                </div>\n",
        "              </div>\n",
        "\n",
        "              <div className=\"hidden print:block\" style={{ fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", fontSize: \"8pt\", fontWeight: 600, letterSpacing: \"0.2em\", textTransform: \"uppercase\", color: AMBER, marginBottom: \"8pt\" }}>\n",
        "                Filed months ({history.length})\n",
        "              </div>\n",
        "\n",
        "              {importError && (\n",
        "                <div style={{ marginBottom: \"8pt\", padding: \"6pt 10pt\", background: \"rgba(122,26,26,0.08)\", border: `1pt solid ${RED}`, borderRadius: \"3pt\", fontSize: \"8pt\", color: RED }}>\n",
        "                  Import failed: {importError}\n",
        "                </div>\n",
        "              )}\n",
        "\n",
        "              {pendingImport && (\n",
        "                <div style={{ marginBottom: \"10pt\", padding: \"10pt 14pt\", background: \"rgba(184,90,62,0.08)\", border: `1pt solid ${AMBER}`, borderRadius: \"4pt\" }}>\n",
        "                  <div style={{ fontSize: \"8pt\", fontWeight: 700, color: DARK, marginBottom: \"6pt\" }}>\n",
        "                    Import {pendingImport.length} record{pendingImport.length != 1 and \"s\" or \"\"} — how would you like to proceed?\n",
        "                  </div>\n",
        "                  <div style={{ fontSize: \"7.5pt\", color: MUTED, marginBottom: \"10pt\", lineHeight: 1.5 }}>\n",
        "                    <strong>Merge</strong> adds only months not already present, leaving existing records untouched.{\" \"}\n",
        "                    <strong>Replace</strong> overwrites all history with the imported file.\n",
        "                  </div>\n",
        "                  <div style={{ display: \"flex\", gap: \"8pt\" }}>\n",
        "                    <button\n",
        "                      type=\"button\"\n",
        "                      onClick={() => handleConfirmImport(\"merge\")}\n",
        "                      style={{ padding: \"4pt 14pt\", background: DARK, color: CREAM, border: \"none\", borderRadius: \"3pt\", fontSize: \"7.5pt\", fontWeight: 700, cursor: \"pointer\" }}\n",
        "                    >\n",
        "                      Merge\n",
        "                    </button>\n",
        "                    <button\n",
        "                      type=\"button\"\n",
        "                      onClick={() => handleConfirmImport(\"replace\")}\n",
        "                      style={{ padding: \"4pt 14pt\", background: AMBER, color: CREAM, border: \"none\", borderRadius: \"3pt\", fontSize: \"7.5pt\", fontWeight: 700, cursor: \"pointer\" }}\n",
        "                    >\n",
        "                      Replace all\n",
        "                    </button>\n",
        "                    <button\n",
        "                      type=\"button\"\n",
        "                      onClick={() => setPendingImport(null)}\n",
        "                      style={{ padding: \"4pt 10pt\", background: \"transparent\", color: MUTED, border: `1pt solid ${RULE}`, borderRadius: \"3pt\", fontSize: \"7.5pt\", cursor: \"pointer\" }}\n",
        "                    >\n",
        "                      Cancel\n",
        "                    </button>\n",
        "                  </div>\n",
        "                </div>\n",
        "              )}\n",
        "\n",
        "              {history.length === 0 ? (\n",
        "                <div style={{ padding: \"14pt 0\", color: MUTED, fontSize: \"9pt\" }}>\n",
        "                  No months filed yet. Use the form above to record the first close.\n",
        "                </div>\n",
        "              ) : (\n",
        "                <table style={{ width: \"100%\", borderCollapse: \"collapse\", fontSize: \"9pt\" }}>\n",
        "                  <thead>\n",
        "                    <tr style={{ borderBottom: `1.5pt solid ${RULE}`, color: MUTED, fontWeight: 600, fontSize: \"7.5pt\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", letterSpacing: \"0.12em\", textTransform: \"uppercase\" }}>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"left\",   width: \"13%\" }}>Month</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"right\",  width: \"15%\" }}>Revenue</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"right\",  width: \"15%\" }}>Expenses</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"right\",  width: \"14%\" }}>Net</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"right\",  width: \"12%\" }}>vs. Plan</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"center\", width: \"11%\" }}>Status</th>\n",
        "                      <th style={{ padding: \"3pt 4pt\", textAlign: \"left\",   width: \"20%\" }}>Note</th>\n",
        "                    </tr>\n",
        "                  </thead>\n",
        "                  <tbody>\n",
        "                    {[...history].reverse().map((rec) => {\n",
        "                      const st = STATUS_STYLES[getStatus(rec.net)];\n",
        "                      const delta = rec.net - SALT_BASELINE_NET;\n",
        "                      return (\n",
        "                        <tr key={rec.month} style={{ borderBottom: `0.5pt solid ${RULE}` }}>\n",
        "                          <td style={{ padding: \"4pt 4pt\", fontWeight: 600 }}>{labelMonth(rec.month)}</td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", textAlign: \"right\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\" } as React.CSSProperties}>{fmt(rec.revenue)}</td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", textAlign: \"right\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\" }}>{fmt(rec.expenses)}</td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", textAlign: \"right\", fontWeight: 700, fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", color: rec.net >= 0 ? DARK : RED }}>\n",
        "                            {rec.net >= 0 ? fmt(rec.net) : `(${fmt(Math.abs(rec.net))})`}\n",
        "                          </td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", textAlign: \"right\", fontFamily: \"'IBM Plex Mono', ui-monospace, monospace\", fontSize: \"8pt\", color: delta >= 0 ? GREEN : RED }}>\n",
        "                            {fmtDelta(delta)}\n",
        "                          </td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", textAlign: \"center\" }}>\n",
        "                            <span style={{\n",
        "                              display: \"inline-block\",\n",
        "                              padding: \"1pt 5pt\",\n",
        "                              borderRadius: \"2pt\",\n",
        "                              background: st.bg,\n",
        "                              color: st.color,\n",
        "                              fontSize: \"7pt\",\n",
        "                              fontWeight: 700,\n",
        "                              textTransform: \"uppercase\",\n",
        "                              letterSpacing: \"0.05em\",\n",
        "                            }}>\n",
        "                              {st.label}\n",
        "                            </span>\n",
        "                          </td>\n",
        "                          <td style={{ padding: \"4pt 4pt\", fontSize: \"8pt\", color: MUTED, fontStyle: \"italic\" }}>\n",
        "                            {rec.note || \"—\"}\n",
        "                          </td>\n",
        "                        </tr>\n",
        "                      );\n",
        "                    })}\n",
        "                  </tbody>\n",
        "                </table>\n",
        "              )}\n",
        "            </div>\n",
        "\n",
        "            <div style={{ marginBottom: \"14pt\", border: `1pt solid ${prevQtrUnder ? \"#7a1a1a\" : priorComplete ? \"#2a6b3e\" : RULE}`, borderRadius: \"3pt\", padding: \"10pt 14pt\", background: prevQtrUnder ? \"rgba(122,26,26,0.05)\" : priorComplete ? \"rgba(42,107,62,0.05)\" : \"rgba(31,61,46,0.03)\" }}>\n",
        "              <div style={{ display: \"flex\", justifyContent: \"space-between\", alignItems: \"flex-start\", flexWrap: \"wrap\", gap: \"8pt\" }}>\n",
        "                <div>\n",
        "                  <div style={{ fontSize: \"7pt\", fontWeight: 700, letterSpacing: \"0.2em\", textTransform: \"uppercase\", color: AMBER, marginBottom: \"4pt\" }}>\n",
        "                    Rule 02 — Prior-quarter revenue signal\n",
        "                  </div>\n",
        "                  <div style={{ fontSize: \"9pt\", color: TEXT, lineHeight: 1.5 }}>\n",
        "                    {!priorComplete\n",
        "                      ? `Prior quarter incomplete — ${priorChain.length} of 3 months filed. Cannot determine trigger.`\n",
        "                      : prevQtrUnder\n",
        "                      ? `Prior quarter net ${fmtExact(priorMetrics.totalNet)} is below the quarterly floor ${fmtExact(SALT_BASELINE_NET * 3)}. Wholesale reprice / drop trigger is active.`\n",
        "                      : `Prior quarter net ${fmtExact(priorMetrics.totalNet)} meets the quarterly floor ${fmtExact(SALT_BASELINE_NET * 3)}. Trigger clear.`\n",
        "                    }\n",
        "                  </div>\n",
        "                </div>\n",
        "                <span style={{\n",
        "                  display: \"inline-block\",\n",
        "                  padding: \"2pt 10pt\",\n",
        "                  borderRadius: \"3pt\",\n",
        "                  fontSize: \"7pt\",\n",
        "                  fontWeight: 700,\n",
        "                  letterSpacing: \"0.1em\",\n",
        "                  textTransform: \"uppercase\",\n",
        "                  background: !priorComplete ? \"rgba(31,61,46,0.06)\" : prevQtrUnder ? \"rgba(122,26,26,0.10)\" : \"rgba(42,107,62,0.10)\",\n",
        "                  color: !priorComplete ? MUTED : prevQtrUnder ? RED : GREEN,\n",
        "                }}>\n",
        "                  {!priorComplete ? \"incomplete\" : prevQtrUnder ? \"triggered\" : \"clear\"}\n",
        "                </span>\n",
        "              </div>\n",
        "            </div>\n",
        "\n",
        "            {/* ── Planning reference ─────────────────────────────────────────── */}\n",
        "            <div style={{ background: \"rgba(31,61,46,0.05)\", border: `1pt solid ${RULE}`, borderRadius: \"3pt\", padding: \"10pt 14pt\" }}>\n",
        "              <div style={{ fontSize: \"7pt\", fontWeight: 700, letterSpacing: \"0.2em\", textTransform: \"uppercase\", color: AMBER, marginBottom: \"6pt\" }}>\n",
        "                Planning reference — SALT-01\n",
        "              </div>\n",
        "              <div style={{ display: \"grid\", gridTemplateColumns: \"1fr 1fr 1fr\", gap: \"10pt\" }}>\n",
        "                {[\n",
        "                  { label: \"Baseline net / month\", value: fmt(SALT_BASELINE_NET), detail: \"Planning assumption net after direct costs\" },\n",
        "                  { label: \"Watch threshold\",       value: fmt(Math.round(SALT_BASELINE_NET * 0.7)), detail: \"70 % of baseline — trigger a note\" },\n",
        "                  { label: \"Below threshold\",       value: `< ${fmt(Math.round(SALT_BASELINE_NET * 0.7))}`, detail: \"Below 70 % — flag on the one-pager\" },\n",
        "                ].map(s => (\n",
        "                  <div key={s.label}>\n",
        "                    <div style={{ fontSize: \"7pt\", fontWeight: 700, letterSpacing: \"0.15em\", textTransform: \"uppercase\", color: MUTED, marginBottom: \"2pt\" }}>{s.label}</div>\n",
        "                    <div style={{ fontSize: \"12pt\", fontWeight: 700, color: DARK, fontFamily: \"Fraunces, Georgia, serif\", marginBottom: \"2pt\" }}>{s.value}</div>\n",
        "                    <div style={{ fontSize: \"8pt\", color: MUTED, lineHeight: 1.4 }}>{s.detail}</div>\n",
        "                  </div>\n",
        "                ))}\n",
        "              </div>\n",
        "            </div>\n",
        "\n",
        "            {/* Footer */}\n",
        "            <div style={{ marginTop: \"18pt\", borderTop: `1pt solid rgba(31,61,46,0.12)`, paddingTop: \"8pt\", display: \"flex\", justifyContent: \"space-between\" }}>\n",
        "              <div style={{ fontSize: \"7pt\", color: MUTED, letterSpacing: \"0.06em\", textTransform: \"uppercase\" }}>\n",
        "                Headwaters Development Services · SALT-01 Monthly Close\n",
        "              </div>\n",
        "              <div style={{ fontSize: \"7pt\", color: MUTED }}>\n",
        "                History stored locally — use Download CSV / JSON to back up or audit\n",
        "              </div>\n",
        "            </div>\n",
        "\n",
        "          </div>\n",
        "        </div>\n",
        "      </div>\n",
        "    </>\n",
        "  );\n",
        "}\n"
    ]

    new_content = start_lines + resolved_body
    
    with open(path, "w", encoding="utf-8") as f:
        f.writelines(new_content)

if __name__ == "__main__":
    resolve()
