export const SEVEN_DIMENSIONS = [
  {
    id: "physical",
    name: "Physical / Material",
    symbol: "⊡",
    prompt: "What tangible things — resources, bodies, land, tools — does this touch?",
    check: "Does it respect the physical headwaters and survival floor (Bucket 1)?",
    gord: "Can a northern person see the real cost on one page?",
    leadSeat: "Saltbox",
    leadSeatId: "saltbox",
  },
  {
    id: "biological",
    name: "Biological / Living Systems",
    symbol: "🌱",
    prompt: "How does this affect health, ecology, vitality, or the living bond?",
    check: "Does it keep life flowing or drain the watershed?",
    gord: "",
    leadSeat: "Community",
    leadSeatId: "community-econ",
  },
  {
    id: "psychological",
    name: "Psychological / Narrative",
    symbol: "🧠",
    prompt: "What stories or inner parts does this touch?",
    check: "Does it honour personal narratives and avoid fragmentation?",
    gord: "",
    leadSeat: "Smith",
    leadSeatId: "grok",
  },
  {
    id: "quantum",
    name: "Quantum / Probabilistic",
    symbol: "⟳",
    prompt: "What branching possibilities or uncertainties does this open?",
    check: "Are we comfortable with the full range of futures this activates?",
    gord: "",
    leadSeat: "Systems",
    leadSeatId: "systems",
  },
  {
    id: "soul",
    name: "Soul / Spiritual",
    symbol: "☷",
    prompt: "Does this preserve essence or risk extraction?",
    check: "Any risk to the unmediated heart-to-heart connection?",
    gord: "",
    leadSeat: "Ishmael",
    leadSeatId: "ishmael",
  },
  {
    id: "collective",
    name: "Collective / Inter-subjective",
    symbol: "⌂",
    prompt: "How does this affect trust circles and mutual aid?",
    check: "Does it build ownership or does it create dependency?",
    gord: "",
    leadSeat: "Community",
    leadSeatId: "community-econ",
  },
  {
    id: "future",
    name: "Future / Timelines / Long View",
    symbol: "🌳",
    prompt: "What does this leave for the person who inherits it seven generations from now?",
    check: "Seven-Generation Scrutiny + Honey Principle",
    gord: "Does this pass the long view at this table?",
    leadSeat: "Ishmael",
    leadSeatId: "ishmael",
  },
] as const;

export type SevenDimension = (typeof SEVEN_DIMENSIONS)[number];
export type SevenDMode = "sounding" | "working" | "review";
