const palette = {
  ink: "#1f3d2e",
  cream: "#f4ede0",
  paper: "#ede4d2",
  sand: "#c8bfa7",
  stone: "#6b7665",
  rust: "#b85a3e",
};

const colors = {
  light: {
    text: palette.ink,
    tint: palette.ink,
    background: palette.cream,
    foreground: palette.ink,
    card: palette.paper,
    cardForeground: palette.ink,
    primary: palette.ink,
    primaryForeground: palette.cream,
    secondary: palette.paper,
    secondaryForeground: palette.ink,
    muted: palette.sand,
    mutedForeground: palette.stone,
    accent: palette.sand,
    accentForeground: palette.ink,
    destructive: "#7a2e2e",
    destructiveForeground: palette.cream,
    border: palette.sand,
    input: palette.sand,
    rule: "#d4ccb6",
    pullQuote: palette.stone,
    chrome: "rgba(244,237,224,0.94)",
    chromeBorder: "rgba(31,61,46,0.10)",
    rust: palette.rust,
  },
  dark: {
    text: "#e8e0cf",
    tint: "#e8e0cf",
    background: "#0e1a14",
    foreground: "#e8e0cf",
    card: "#16261d",
    cardForeground: "#e8e0cf",
    primary: "#e8e0cf",
    primaryForeground: "#0e1a14",
    secondary: "#16261d",
    secondaryForeground: "#e8e0cf",
    muted: "#3b554a",
    mutedForeground: "#9aa89c",
    accent: "#3b554a",
    accentForeground: "#e8e0cf",
    destructive: "#c87878",
    destructiveForeground: "#0e1a14",
    border: "#2a3d33",
    input: "#2a3d33",
    rule: "#26382e",
    pullQuote: "#9aa89c",
    chrome: "rgba(14,26,20,0.94)",
    chromeBorder: "rgba(232,224,207,0.10)",
    rust: "#c97055",
  },
  radius: 4,
};

export default colors;
