import { sql } from "drizzle-orm";
import {
  pgTable,
  text,
  uuid,
  timestamp,
  index,
  primaryKey,
  check,
} from "drizzle-orm/pg-core";

// ---------- wordpile_piles ----------
//
// One row per community pile, owned by a single Clerk user. We mirror the
// Clerk user id directly on the row (no separate user table) — this is a
// single-tenant tool with no roles, no sharing, no admin UI, so a join
// table just adds friction.
//
// `id` is generated by the client (UUID) so that locally-created piles can
// be uploaded after sign-in without an id remap.
export const wordpilePilesTable = pgTable(
  "wordpile_piles",
  {
    id: uuid("id").primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    ownerIdx: index("wordpile_piles_owner_idx").on(t.clerkUserId),
  }),
);

// ---------- wordpile_words ----------
//
// One row per word inside a pile. `bucket` is a free-form text column with
// the four-value enum enforced at the application layer (matches the
// original localStorage shape so we never need a migration just to add a
// fifth bucket).
export const wordpileWordsTable = pgTable(
  "wordpile_words",
  {
    id: uuid("id").primaryKey(),
    pileId: uuid("pile_id")
      .notNull()
      .references(() => wordpilePilesTable.id, { onDelete: "cascade" }),
    word: text("word").notNull(),
    note: text("note").notNull().default(""),
    bucket: text("bucket").notNull().default("unsorted"),
    saferAlternative: text("safer_alternative").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    pileIdx: index("wordpile_words_pile_idx").on(t.pileId),
  }),
);

// ---------- wordpile_deletions ----------
//
// Tombstones for piles and words this user has explicitly deleted. The
// /sync endpoint consults this table so a stale device that still has a
// deleted pile cached locally cannot resurrect it by uploading its old
// snapshot. (Without tombstones, /sync sees "incoming pile X has no
// matching server row" and inserts it back — see the comment in
// `routes/wordpile.ts`.)
//
// `kind` is "pile" | "word" — enforced at the application layer rather
// than as a Postgres enum so we don't have to ship a migration just to
// add a third tombstoned shape later.
//
// The composite primary key (clerkUserId, kind, id) means each user owns
// their own tombstone namespace and a re-deletion of the same id just
// updates the existing row instead of creating a duplicate.
export const wordpileDeletionsTable = pgTable(
  "wordpile_deletions",
  {
    clerkUserId: text("clerk_user_id").notNull(),
    kind: text("kind").notNull(),
    id: uuid("id").notNull(),
    deletedAt: timestamp("deleted_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    pk: primaryKey({ columns: [t.clerkUserId, t.kind, t.id] }),
    ownerIdx: index("wordpile_deletions_owner_idx").on(t.clerkUserId),
    // Belt-and-suspenders: the route layer only ever writes "pile" or
    // "word", but a CHECK keeps a future bug from silently storing
    // garbage that the /sync skip-lookup would then ignore.
    kindCheck: check(
      "wordpile_deletions_kind_check",
      sql`${t.kind} IN ('pile', 'word')`,
    ),
  }),
);

// ---------- wordpile_short_links ----------
//
// Server-stored share links keyed by an unguessable short slug. The
// fragment-based share URLs (`#data=...`) keep the pile contents fully
// client-side and work without ever touching the server, but they get
// long fast and some messaging apps mangle anything past a few KB.
// Short links trade that privacy property for a tiny URL: the gzip+
// base64 payload is stored opaquely on the server keyed by the slug,
// and anyone with the slug can fetch + decode it.
//
// Design choices:
//   - `slug` is the PK so a `GET /short-links/:slug` is a single
//     primary-key lookup, no per-user join required (the resolve
//     endpoint is anonymous on purpose — share-link recipients aren't
//     necessarily users of this app).
//   - `clerkUserId` is the owner who can revoke. The resolve endpoint
//     never exposes it.
//   - `pileId` is a hint only (no FK) so deleting the pile doesn't
//     cascade-revoke its share links — a practitioner who deleted a
//     pile locally can still revoke its outstanding short links.
//   - `pileName` is captured at create time so the "your short links"
//     list stays meaningful even after the pile is renamed/deleted.
//   - `payload` is the same opaque base64url string the fragment link
//     would carry — the server never has to parse the contents.
export const wordpileShortLinksTable = pgTable(
  "wordpile_short_links",
  {
    slug: text("slug").primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    pileId: uuid("pile_id"),
    pileName: text("pile_name").notNull().default(""),
    payload: text("payload").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    ownerIdx: index("wordpile_short_links_owner_idx").on(t.clerkUserId),
  }),
);

export type WordpilePileRow = typeof wordpilePilesTable.$inferSelect;
export type WordpileWordRow = typeof wordpileWordsTable.$inferSelect;
export type WordpileDeletionRow = typeof wordpileDeletionsTable.$inferSelect;
export type WordpileShortLinkRow = typeof wordpileShortLinksTable.$inferSelect;
