import {
  pgTable,
  text,
  uuid,
  timestamp,
  index,
} from "drizzle-orm/pg-core";

// ---------- wordpile_piles ----------
//
// One row per community pile, owned by a single Clerk user. We mirror the
// Clerk user id directly on the row (no separate user table) — this is a
// single-tenant tool with no roles, no sharing, no admin UI, so a join
// table just adds friction.
//
// `id` is generated by the client (UUID) so that locally-created piles can
// be uploaded after sign-in without an id remap.
export const wordpilePilesTable = pgTable(
  "wordpile_piles",
  {
    id: uuid("id").primaryKey(),
    clerkUserId: text("clerk_user_id").notNull(),
    name: text("name").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    ownerIdx: index("wordpile_piles_owner_idx").on(t.clerkUserId),
  }),
);

// ---------- wordpile_words ----------
//
// One row per word inside a pile. `bucket` is a free-form text column with
// the four-value enum enforced at the application layer (matches the
// original localStorage shape so we never need a migration just to add a
// fifth bucket).
export const wordpileWordsTable = pgTable(
  "wordpile_words",
  {
    id: uuid("id").primaryKey(),
    pileId: uuid("pile_id")
      .notNull()
      .references(() => wordpilePilesTable.id, { onDelete: "cascade" }),
    word: text("word").notNull(),
    note: text("note").notNull().default(""),
    bucket: text("bucket").notNull().default("unsorted"),
    saferAlternative: text("safer_alternative").notNull().default(""),
    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => ({
    pileIdx: index("wordpile_words_pile_idx").on(t.pileId),
  }),
);

export type WordpilePileRow = typeof wordpilePilesTable.$inferSelect;
export type WordpileWordRow = typeof wordpileWordsTable.$inferSelect;
